### ISSUE TITLE
feat: add word counter

### ISSUE THREAD

**Issue by thijsfranck** [thijsfranck/courageous-comets#11]
Set up a function that, given a piece of text, calculates its uniqueness based on the occurrence of common words. The fewer common words, the greater the uniqueness. 

- Set up a sentence tokenizer. The tokenizer should include a stemmer and eliminate common words like "the" and "I".
- Set up a word counter
- Store updated word counts in the database
- Return the count for each token

**Comment by elfkuzco** [comment]
I did a bit of digging and it seems like we could use [NTLK](https://www.nltk.org/howto/stem.html) to stem and tokenize words.

Also found [Sentence Transformers](https://www.sbert.net/docs/installation.html) which we can use to create vector representations of the message. I suppose we could store the message ID in the hash that would contain this text and create the discord link to the message on demand.

What do you think? @thijsfranck @isaa-ctaylor

**Comment by thijsfranck** [comment]
There is also a stemmer/tokenizer built into Redis:

https://redis.io/docs/latest/develop/interact/search-and-query/advanced-concepts/stemming/

I imagine this might scale better since it would require fewer database interactions. But I have no idea how well it works (never used it).
